### ISSUE TITLE
Possibility to dual license nss-pem?

### ISSUE THREAD

**Issue by davemeurer** [kdudka/nss-pem#3]
Hello Kamil,

Would it be a possibility to dual license nss-pem with another license like GPL, LGPL, MIT, BSD?  It appears MPL is not terribly popular and trusted by some orgs. 

Or if you don't want to dual license, can you grant me permission to use another specific license?

Thanks for the consideration!

**Comment by kdudka** [comment]
For me personally, all the mentioned licenses are perfectly fine.  The problem is that I am not the original author of nss-pem, so I am not the one who can change the license.  The code was originally intended to be included in Mozilla's distribution of NSS -- see https://bugzilla.mozilla.org/402712

So I guess that using the same license as NSS uses should be possible if the original authors agree.  I can see the following text in the license file of NSS itself:
```
Note on GPL Compatibility
-------------------------

The MPL 2, section 3.3, permits you to combine NSS with code under the GNU
General Public License (GPL) version 2, or any later version of that
license, to make a Larger Work, and distribute the result under the GPL.
The only condition is that you must also make NSS, and any changes you
have made to it, available to recipients under the terms of the MPL 2 also.

Anyone who receives the combined code from you does not have to continue
to dual licence in this way, and may, if they wish, distribute under the
terms of either of the two licences - either the MPL alone or the GPL
alone. However, we discourage people from distributing copies of NSS under
the GPL alone, because it means that any improvements they make cannot be
reincorporated into the main version of NSS. There is never a need to do
this for license compatibility reasons.

Note on LGPL Compatibility
--------------------------

The above also applies to combining MPLed code in a single library with
code under the GNU Lesser General Public License (LGPL) version 2.1, or
any later version of that license. If the LGPLed code and the MPLed code
are not in the same library, then the copyleft coverage of the two
licences does not overlap, so no issues arise.
```

**Comment by davemeurer** [comment]
Appreciate the quick response, Kamil.  Understood, thank you!

**Comment by davemeurer** [comment]
Hi Kamil,

I just noticed something in the code.  It looks like most of the files do allow licensing under GPL 2.0 or LGPL 2.1.  For example, in nsspem.h, the license block shows the following.  So I think we are good! 

* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is the Netscape security libraries.
 *
 * The Initial Developer of the Original Code is
 * Netscape Communications Corporation.
 * Portions created by the Initial Developer are Copyright (C) 1994-2000
 * the Initial Developer. All Rights Reserved.
 * Portions created by Red Hat, Inc, are Copyright (C) 2005
 *
 * Contributor(s):
 *   Rob Crittenden (rcritten@redhat.com)
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

**Comment by kdudka** [comment]
Indeed, the code seems to already be GPL-compatible as it is.  Thank you for pointing it out!
