### ISSUE TITLE
CK?_NETSCAPE_? depreciated, should be replaced with CK?_NSS_?

### ISSUE THREAD

**Issue by pomac303** [kdudka/nss-pem#6]
commit ba931199b924a2eac38899d04b04eedc75771546
Author: Robert Relyea <rrelyea@redhat.com>
Date:   Tue Feb 18 11:47:29 2020 -0800

    Bug 1603628 Update NSS to handle PKCS #11 v3.0 r=daiki r=mhoye
    
    https://phabricator.services.mozilla.com/D63241
    
    This patch implements the first phase: updating the headers.
    
    lib/util/pkcs11.h
    lib/util/pkcs11f.h
    lib/util/pkcs11t.h
    
    Were updated using the released OASIS PKCS #11 v3.0 header files.
    lib/util/pkcs11n.h was updated to finally deprecate all uses of CK?_NETSCAPE_?.
    
    A new define as added: NSS_PKCS11_2_0_COMPAT. If it's defined, the small
    semantic changes (including the removal of deprecated defines) between the
    NSS PKCS #11 v2 header file and the new PKCS #11 v3 are reverted in favor of
    the PKCS #11 v2 definitions. This include the removal of CK?_NETSCAPE_? in
    favor of CK?_NSS_?.
... 

More can be read in the actual git repo, anyway, here is a patch:
[netscape.txt](https://github.com/kdudka/nss-pem/files/5041514/netscape.txt)

**Comment by kdudka** [comment]
Thank you for letting me know!  Pull request https://github.com/kdudka/nss-pem/pull/7 should fix this.

**Comment by kdudka** [comment]
Now I see that you also attached the patch!  PR resubmitted with you being the author...

**Comment by pomac303** [comment]
Thanks, I mainly care about it being fixed ;)

I don't know why GitHub didn't support sending diffs... But handle docx?!

**Comment by kdudka** [comment]
As long as the service is for free, I am not so strict in my requirements on it :)  Merging, thanks for the contribution!
