### ISSUE TITLE
Inclusion of list.h seems to make this project effectively GPL2

### ISSUE THREAD

**Issue by tobijk** [kdudka/nss-pem#8]
I'm a bit confused with respect to the licensing. I see that the sources are licensed under "MPL 1.1/GPL 2.0/LGPL 2.1". And the `COPYING` file contains the MPL1.1. However, through the use of `list.h`, which is exclusively GPL2 licensed, it seems that any binary produced would have to be GPL2, as well? Am I misunderstanding the mechanics of this?

**Comment by kdudka** [comment]
I tend to agree.  If some source files support multiple licenses (including GPLv2) and some source file(s) support GPLv2 only, then it would make sense to treat the resulting binary as GPLv2.  I am not a lawyer though.

**Comment by tobijk** [comment]
Then effectively a license change from "MPL 1.1/GPL 2.0/LGPL 2.1" to GPL2 (pertaining to the binary artifact) was introduced in a patch level release from 1.0.4 to 1.0.5. I understand that whoever uses this module has to do their own license clearing. But if one were just upgrading from 1.0.4, one would have hardly noticed.

I think it would be good to put a notice at the top of COPYING and bump at least the minor version (as this is akin to an ABI break in license land), so that users have a chance of noticing.

As far as compatibility with libnss is concerned, I do not think, there is a problem. The module does not link against nss, though it certainly includes nss headers and may therefore include nss code. Since NSS is MPL2 and MPL2 is GPL2-compatible, it should be OK to distribute the module under the GPL2. I assume since the module is dynamically loaded, the license of the nss-pem module does not affect libnss. I am not entirely sure about what this means for e.g. curl compiled against libnss and relying on the functionality of this module to use the system's certificate store. I assume it should be fine, since the module is side-loaded, but I'm not a lawyer, either.

**Comment by kdudka** [comment]
The `COPYING` file is a verbatim copy of the MPL license, which I would prefer not to modify.  We can mention it in the `README` file and/or provide `COPYING` files for both MPL and GPL.

**Comment by tobijk** [comment]
Sounds good.

**Comment by kdudka** [comment]
Then it should be easy.  I have opened pull request #9 to sort this out.  Feedback is welcome.
